# Generated by Django 5.0.1 on 2024-01-22 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('6dff5dcd-1acf-433d-8d1e-2151b39ef26d'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Имя по умолчанию', help_text='Здесь заполняется имя рекламы', max_length=50, unique=True, verbose_name='Имя рекламы')),
                ('status', models.CharField(choices=[(None, 'Выберите статус рекламы'), ('s', 'Продано'), ('a', 'Активна'), ('c', 'Отменена')], default='a', max_length=1, verbose_name='Статус рекламы')),
                ('content', models.TextField(blank=True, null=True, unique_for_year='published', verbose_name='Содержание рекламы')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
