# Generated by Django 5.0.1 on 2024-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание рекламы'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя рекламы'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
