# Generated by Django 5.0 on 2024-01-23 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5bf2fe07-f1fc-4925-884c-b40526bf2bc0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
