# Generated by Django 5.0 on 2024-01-23 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('168241c8-0784-44c7-9c28-a9aa6acb8517'), editable=False, primary_key=True, serialize=False),
        ),
    ]
