# Generated by Django 5.0.1 on 2024-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_category_ad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('s', 'Продано'), ('a', 'Активна'), ('c', 'Отменена')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(blank=True, null=True, unique_for_year='published', verbose_name='Содержание рекламы'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(default='Имя по умолчанию', help_text='Здесь заполняется имя рекламы', max_length=50, unique=True, verbose_name='Имя рекламы'),
        ),
    ]
