# Generated by Django 5.0.1 on 2024-01-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[(None, 'Выберите статус рекламы'), ('s', 'Продано'), ('a', 'Активна'), ('c', 'Отменена')], default='a', max_length=1, verbose_name='Статус рекламы'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.author'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ManyToManyField(to='ads.category'),
        ),
    ]
