# Generated by Django 5.0.1 on 2024-01-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['price'], 'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
    ]
